use std::{convert::From,fmt::Debug};
use  Color::*;
//const ESCAPE:&str = "\x1b";

//static UNDERLINE:&str = "\x1b[4m";
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Color {
    Black,
    Red,
    Green,
    Yellow,
    Blue,
    Magenta,
    Cyan,
    LightGray,
    DarkGray,
    LightRed,
    LightGreen,
    LightYellow,
    LightBlue,
    LightMagenta,
    LightCyan,
    White,
    Grey0,
    NavyBlue,
    DarkBlue,
    Blue3a,
    Blue3b,
    Blue1,
    DarkGreen,
    DeepSkyBlue4a,
    DeepSkyBlue4b,
    DeepSkyBlue4c,
    DodgerBlue3,
    DodgerBlue2,
    Green4,
    SpringGreen4,
    Turquoise4,
    DeepSkyBlue3a,
    DeepSkyBlue3b,
    DodgerBlue1,
    Green3a,
    SpringGreen3a,
    DarkCyan,
    LightSeaGreen,
    DeepSkyBlue2,
    DeepSkyBlue1,
    Green3b,
    SpringGreen3b,
    SpringGreen2a,
    Cyan3,
    DarkTurquoise,
    Turquoise2,
    Green1,
    SpringGreen2b,
    SpringGreen1,
    MediumSpringGreen,
    Cyan2,
    Cyan1,
    DarkRed1,
    DeepPink4a,
    Purple4a,
    Purple4b,
    Purple3,
    BlueViolet,
    Orange4a,
    Grey37,
    MediumPurple4,
    SlateBlue3a,
    SlateBlue3b,
    RoyalBlue1,
    Chartreuse4,
    DarkSeaGreen4a,
    PaleTurquoise4,
    SteelBlue,
    SteelBlue3,
    CornflowerBlue,
    Chartreuse3a,
    DarkSeaGreen4b,
    CadetBlue2,
    CadetBlue1,
    SkyBlue3,
    SteelBlue1a,
    Chartreuse3b,
    PaleGreen3a,
    SeaGreen3,
    Aquamarine3,
    MediumTurquoise,
    SteelBlue1b,
    Chartreuse2a,
    SeaGreen2,
    SeaGreen1a,
    SeaGreen1b,
    Aquamarine1a,
    DarkSlateGray2,
    DarkRed2,
    DeepPink4b,
    DarkMagenta1,
    DarkMagenta2,
    DarkViolet1a,
    Purple1a,
    Orange4b,
    LightPink4,
    Plum4,
    MediumPurple3a,
    MediumPurple3b,
    SlateBlue1,
    Yellow4a,
    Wheat4,
    Grey53,
    LightSlateGrey,
    MediumPurple,
    LightSlateBlue,
    Yellow4b,
    DarkOliveGreen3a,
    DarkGreenSea,
    LightSkyBlue3a,
    LightSkyBlue3b,
    SkyBlue2,
    Chartreuse2b,
    DarkOliveGreen3b,
    PaleGreen3b,
    DarkSeaGreen3a,
    DarkSlateGray3,
    SkyBlue1,
    Chartreuse1,
    LightGreen2,
    LightGreen3,
    PaleGreen1a,
    Aquamarine1b,
    DarkSlateGray1,
    Red3a,
    DeepPink4c,
    MediumVioletRed,
    Magenta3a,
    DarkViolet1b,
    Purple1b,
    DarkOrange3a,
    IndianRed1a,
    HotPink3a,
    MediumOrchid3,
    MediumOrchid,
    MediumPurple2a,
    DarkGoldenrod,
    LightSalmon3a,
    RosyBrown,
    Grey63,
    MediumPurple2b,
    MediumPurple1,
    Gold3a,
    DarkKhaki,
    NavajoWhite3,
    Grey69,
    LightSteelBlue3,
    LightSteelBlue,
    Yellow3a,
    DarkOliveGreen3,
    DarkSeaGreen3b,
    DarkSeaGreen2,
    LightCyan3,
    LightSkyBlue1,
    GreenYellow,
    DarkOliveGreen2,
    PaleGreen1b,
    DarkSeaGreen5b,
    DarkSeaGreen5a,
    PaleTurquoise1,
    Red3b,
    DeepPink3a,
    DeepPink3b,
    Magenta3b,
    Magenta3c,
    Magenta2a,
    DarkOrange3b,
    IndianRed1b,
    HotPink3b,
    HotPink2,
    Orchid,
    MediumOrchid1a,
    Orange3,
    LightSalmon3b,
    LightPink3,
    Pink3,
    Plum3,
    Violet,
    Gold3b,
    LightGoldenrod3,
    Tan,
    MistyRose3,
    Thistle3,
    Plum2,
    Yellow3b,
    Khaki3,
    LightGoldenrod2a,
    LightYellow3,
    Grey84,
    LightSteelBlue1,
    Yellow2,
    DarkOliveGreen1a,
    DarkOliveGreen1b,
    DarkSeaGreen1,
    Honeydew2,
    LightCyan1,
    Red1,
    DeepPink2,
    DeepPink1a,
    DeepPink1b,
    Magenta2b,
    Magenta1,
    OrangeRed1,
    IndianRed1c,
    IndianRed1d,
    HotPink1a,
    HotPink1b,
    MediumOrchid1b,
    DarkOrange,
    Salmon1,
    LightCoral,
    PaleVioletRed1,
    Orchid2,
    Orchid1,
    Orange1,
    SandyBrown,
    LightSalmon1,
    LightPink1,
    Pink1,
    Plum1,
    Gold1,
    LightGoldenrod2b,
    LightGoldenrod2c,
    NavajoWhite1,
    MistyRose1,
    Thistle1,
    Yellow1,
    LightGoldenrod1,
    Khaki1,
    Wheat1,
    CornSilk1,
    Grey100,
    Grey3,
    Grey7,
    Grey11,
    Grey15,
    Grey19,
    Grey23,
    Grey27,
    Grey30,
    Grey35,
    Grey39,
    Grey42,
    Grey46,
    Grey50,
    Grey54,
    Grey58,
    Grey62,
    Grey66,
    Grey70,
    Grey74,
    Grey78,
    Grey82,
    Grey85,
    Grey89,
    Grey93,
}

impl From<usize> for Color {
    fn from(num: usize) -> Self {
        match num {
            0  => Black,
            1  => Red,
            2  => Green,
            3  => Yellow,
            4  => Blue,
            5  => Magenta,
            6  => Cyan,
            7  => LightGray,
            8  => DarkGray,
            9  => LightRed,
            10  => LightGreen,
            11  => LightYellow,
            12  => LightBlue,
            13  => LightMagenta,
            14  => LightCyan,
            15  => White,
            16  => Grey0,
            17  => NavyBlue,
            18  => DarkBlue,
            19  => Blue3a,
            20  => Blue3b,
            21  => Blue1,
            22 => DarkGreen,
            23  => DeepSkyBlue4a,
            24  => DeepSkyBlue4b,
            25  => DeepSkyBlue4c,
            26  => DodgerBlue3,
            27  => DodgerBlue2,
            28  => Green4,
            29 => SpringGreen4,
            30  => Turquoise4,
            31  => DeepSkyBlue3a,
            32  => DeepSkyBlue3b,
            33  => DodgerBlue1,
            34  => Green3a,
            35  => SpringGreen3a,
            36  => DarkCyan,
            37  => LightSeaGreen,
            38  => DeepSkyBlue2,
            39  => DeepSkyBlue1,
            40  => Green3b,
            41  => SpringGreen3b,
            42  => SpringGreen2a,
            43  => Cyan3,
            44  => DarkTurquoise,
            45  => Turquoise2,
            46  => Green1,
            47  => SpringGreen2b,
            48  => SpringGreen1,
            49  => MediumSpringGreen,
            50  => Cyan2,
            51  => Cyan1,
            52  => DarkRed1,
            53  => DeepPink4a,
            54  => Purple4a,
            55  => Purple4b,
            56  => Purple3,
            57  => BlueViolet,
            58  => Orange4a,
            59  => Grey37,
            60  => MediumPurple4,
            61  => SlateBlue3a,
            62  => SlateBlue3b,
            63  => RoyalBlue1,
            64  => Chartreuse4,
            65  => DarkSeaGreen4a,
            66  => PaleTurquoise4,
            67  => SteelBlue,
            68  => SteelBlue3,
            69  => CornflowerBlue,
            70  => Chartreuse3a,
            71  => DarkSeaGreen4b,
            72  => CadetBlue2,
            73  => CadetBlue1,
            74  => SkyBlue3,
            75  => SteelBlue1a,
            76  => Chartreuse3b,
            77  => PaleGreen3a,
            78  => SeaGreen3,
            79  => Aquamarine3,
            80  => MediumTurquoise,
            81  => SteelBlue1b,
            82  => Chartreuse2a,
            83  => SeaGreen2,
            84  => SeaGreen1a,
            85  => SeaGreen1b,
            86  => Aquamarine1a,
            87  => DarkSlateGray2,
            88  => DarkRed2,
            89  => DeepPink4b,
            90  => DarkMagenta1,
            91  => DarkMagenta2,
            92  => DarkViolet1a,
            93  => Purple1a,
            94  => Orange4b,
            95  => LightPink4,
            96  => Plum4,
            97  => MediumPurple3a,
            98  => MediumPurple3b,
            99  => SlateBlue1,
            100  => Yellow4a,
            101  => Wheat4,
            102  => Grey53,
            103  => LightSlateGrey,
            104  => MediumPurple,
            105  => LightSlateBlue,
            106  => Yellow4b,
            107  => DarkOliveGreen3a,
            108  => DarkGreenSea,
            109  => LightSkyBlue3a,
            110  => LightSkyBlue3b,
            111  => SkyBlue2,
            112  => Chartreuse2b,
            113  => DarkOliveGreen3b,
            114  => PaleGreen3b,
            115  => DarkSeaGreen3a,
            116  => DarkSlateGray3,
            117  => SkyBlue1,
            118  => Chartreuse1,
            119  => LightGreen2,
            120  => LightGreen3,
            121  => PaleGreen1a,
            122  => Aquamarine1b,
            123  => DarkSlateGray1,
            124  => Red3a,
            125  => DeepPink4c,
            126  => MediumVioletRed,
            127  => Magenta3a,
            128  => DarkViolet1b,
            129  => Purple1b,
            130  => DarkOrange3a,
            131  => IndianRed1a,
            132  => HotPink3a,
            133  => MediumOrchid3,
            134  => MediumOrchid,
            135  => MediumPurple2a,
            136  => DarkGoldenrod,
            137  => LightSalmon3a,
            138  => RosyBrown,
            139  => Grey63,
            140  => MediumPurple2b,
            141  => MediumPurple1,
            142  => Gold3a,
            143  => DarkKhaki,
            144  => NavajoWhite3,
            145  => Grey69,
            146  => LightSteelBlue3,
            147  => LightSteelBlue,
            148  => Yellow3a,
            149  => DarkOliveGreen3,
            150  => DarkSeaGreen3b,
            151  => DarkSeaGreen2,
            152  => LightCyan3,
            153  => LightSkyBlue1,
            154  => GreenYellow,
            155  => DarkOliveGreen2,
            156  => PaleGreen1b,
            157  => DarkSeaGreen5b,
            158  => DarkSeaGreen5a,
            159  => PaleTurquoise1,
            160  => Red3b,
            161  => DeepPink3a,
            162  => DeepPink3b,
            163  => Magenta3b,
            164  => Magenta3c,
            165  => Magenta2a,
            166  => DarkOrange3b,
            167  => IndianRed1b,
            168  => HotPink3b,
            169  => HotPink2,
            170  => Orchid,
            171  => MediumOrchid1a,
            172  => Orange3,
            173  => LightSalmon3b,
            174  => LightPink3,
            175  => Pink3,
            176  => Plum3,
            177  => Violet,
            178  => Gold3b,
            179  => LightGoldenrod3,
            180  => Tan,
            181  => MistyRose3,
            182  => Thistle3,
            183  => Plum2,
            184  => Yellow3b,
            185  => Khaki3,
            186  => LightGoldenrod2a,
            187  => LightYellow3,
            188  => Grey84,
            189  => LightSteelBlue1,
            190  => Yellow2,
            191  => DarkOliveGreen1a,
            192  => DarkOliveGreen1b,
            193  => DarkSeaGreen1,
            194  => Honeydew2,
            195  => LightCyan1,
            196  => Red1,
            197  => DeepPink2,
            198  => DeepPink1a,
            199  => DeepPink1b,
            200  => Magenta2b,
            201  => Magenta1,
            202  => OrangeRed1,
            203  => IndianRed1c,
            204  => IndianRed1d,
            205  => HotPink1a,
            206  => HotPink1b,
            207  => MediumOrchid1b,
            208  => DarkOrange,
            209  => Salmon1,
            210 => LightCoral,
            211 => PaleVioletRed1,
            212 => Orchid2,
            213 => Orchid1,
            214 => Orange1,
            215 => SandyBrown,
            216 => LightSalmon1,
            217 => LightPink1,
            218 => Pink1,
            219 => Plum1,
            220  => Gold1,
            221  => LightGoldenrod2b,
            222  => LightGoldenrod2c,
            223  => NavajoWhite1,
            224  => MistyRose1,
            225  => Thistle1,
            226  => Yellow1,
            227  => LightGoldenrod1,
            228  => Khaki1,
            229  => Wheat1,
            230  => CornSilk1,
            231  => Grey100,
            232  => Grey3,
            233  => Grey7,
            234  => Grey11,
            235  => Grey15,
            236  => Grey19,
            237  => Grey23,
            238  => Grey27,
            239  => Grey30,
            240  => Grey35,
            241  => Grey39,
            242  => Grey42,
            243  => Grey46,
            244  => Grey50,
            245  => Grey54,
            246  => Grey58,
            247  => Grey62,
            248  => Grey66,
            249  => Grey70,
            250  => Grey74,
            251  => Grey78,
            252  => Grey82,
            253  => Grey85,
            254  => Grey89,
            255  => Grey93,
            _ => panic!("Index out of bounds!")
        }
    }
}
